version: "3.8"

services:
  nginx_app:
    image: nginx:latest
    depends_on:
      - flask_app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - labos_network

  flask_app:
    build:
      context: ./python_app
    expose:
      - 8080
    networks:
      - labos_network

networks:
  labos_network:
